version: "3.5"

networks:
  mysql_net:

volumes:
  mysql_vol:

services:
  ## Server Mysql
  mysql:
    image: mariadb:10.10
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=rpg
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_TCP_PORT=3306
      - MYSQL_X_PORT=33060
    volumes:
      - mysql_vol:/var/lib/mysql
    networks:
      mysql_net: